### ISSUE TITLE
Delete call incorrect

### ISSUE THREAD

**Issue by williamrenfrew** [madeITBelgium/WordPress-PHP-SDK#1]
https://github.com/madeITBelgium/WordPress-PHP-SDK/blob/02b58e52e22ddee5392b62f6d8a20d79495a9385/src/Object/CustomPost.php#L95

Shouldn't this be `$this->wordpress` ?

**Comment by madeITBelgium** [comment]
Thank you @williamrenfrew I created a fix and a new release 1.2.1.
