### ISSUE TITLE
URL Issue, I belive

### ISSUE THREAD

**Issue by scottunderhill** [madeITBelgium/WordPress-PHP-SDK#2]
Hi, 

I was making a call to the POST api, I noticed

In your code it is 
  $post = new CustomPost($this, 'post');

But to get the list and url it is posts, which I changed to 
  $post = new CustomPost($this, 'posts');

Do you get this error ?

**Comment by madeITBelgium** [comment]
Hi, I checked a few things and you are correct. It is posts. I created a fix.
